name = "Arduino"
grammar = "arduino"
path_suffixes = ["ino"]
line_comments = ["// "]
block_comment = ["/*", "*/"]

[indent_guides]
enabled = true

[[brackets]]
start = "("
end = ")"
close = true
newline = false

[[brackets]]
start = '"'
end = '"'
close = true
newline = false

[[brackets]]
start = "'"
end = "'"
close = true
newline = false

[[brackets]]
start = "["
end = "]"
close = true
newline = false

[[brackets]]
start = "{"
end = "}"
close = true
newline = false

[[brackets]]
start = "/*"
end = "*/"
close = true
newline = false
